-- =========================================================
-- Hashed invitation tokens
-- =========================================================
-- Add a hashed-token column so raw tokens never exist in the database.
-- Raw tokens are generated by edge functions and embedded only in the
-- single accept-invite URL we email out. We store sha256(raw_token) and
-- compare hashes server-side.

-- 1) New column for the SHA-256 hex digest
ALTER TABLE public.team_invitations
  ADD COLUMN IF NOT EXISTS token_hash text;

-- 2) Backfill: for any existing rows, hash the raw token in-place.
--    pgcrypto.digest returns bytea; encode to hex to match what edge
--    functions will produce.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

UPDATE public.team_invitations
SET token_hash = encode(digest(token, 'sha256'), 'hex')
WHERE token_hash IS NULL AND token IS NOT NULL;

-- 3) Make token_hash required + uniquely indexed
ALTER TABLE public.team_invitations
  ALTER COLUMN token_hash SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS team_invitations_token_hash_key
  ON public.team_invitations (token_hash);

-- 4) Drop the raw token column entirely so it is never readable again,
--    even via the service role.
ALTER TABLE public.team_invitations
  DROP COLUMN IF EXISTS token;

-- 5) Update the signup trigger to look up invitations by hash
CREATE OR REPLACE FUNCTION public.handle_new_user_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  _role app_role;
  _invite_token text;
  _invite_hash text;
  _invitation record;
BEGIN
  _invite_token := NEW.raw_user_meta_data ->> 'invitation_token';

  IF _invite_token IS NOT NULL AND _invite_token <> '' THEN
    _invite_hash := encode(digest(_invite_token, 'sha256'), 'hex');

    SELECT * INTO _invitation
    FROM public.team_invitations
    WHERE token_hash = _invite_hash
      AND status = 'pending'
      AND expires_at > now()
    LIMIT 1;
  END IF;

  IF _invitation.id IS NOT NULL THEN
    _role := 'worker'::app_role;
  ELSE
    _role := COALESCE(
      (NEW.raw_user_meta_data ->> 'role')::app_role,
      'manager'::app_role
    );
  END IF;

  IF _role = 'admin' THEN
    _role := 'worker';
  END IF;

  INSERT INTO public.profiles (user_id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''),
    COALESCE(NEW.email, '')
  )
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, _role)
  ON CONFLICT (user_id, role) DO NOTHING;

  IF _invitation.id IS NOT NULL THEN
    INSERT INTO public.team_memberships (user_id, team_id)
    VALUES (NEW.id, _invitation.team_id)
    ON CONFLICT (user_id, team_id) DO UPDATE SET is_active = true;

    UPDATE public.profiles
    SET team_id = _invitation.team_id,
        active_team_id = _invitation.team_id,
        organization_id = (SELECT organization_id FROM public.teams WHERE id = _invitation.team_id)
    WHERE user_id = NEW.id;

    UPDATE public.team_invitations
    SET status = 'accepted'
    WHERE id = _invitation.id;
  END IF;

  RETURN NEW;
END;
$function$;